server:
  address: 0.0.0.0
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
