server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: main-service_route
          uri: lb://main-service
          predicates:
            - Path=/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
