  server:
  address: 0.0.0.0
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # Маршрут для админских эндпоинтов
        - id: admin-service
          uri: lb://main-service
          predicates:
            - Path=/api/admin/**  # Все запросы начинаются с /api/admin
          filters:
            - StripPrefix=2       # Удаляем первые два сегмента (/api/admin → /)

        # Маршрут для приватных эндпоинтов
        - id: private-service
          uri: lb://main-service
          predicates:
            - Path=/api/private/**
          filters:
            - StripPrefix=2

        # Маршрут для публичных эндпоинтов
        - id: public-service
          uri: lb://main-service
          predicates:
            - Path=/api/public/**
          filters:
            - StripPrefix=2

        # Маршрут для общих эндпоинтов без префикса (например, /categories)
        - id: default-service
          uri: lb://main-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
