server:
  address: 0.0.0.0
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # Admin Category Routes
        - id: admin_categories
          uri: http://main-service:8081
          predicates:
            - Path=/admin/categories/**
            - Method=POST,DELETE,PATCH

        # Admin Comment Routes
        - id: admin_comments
          uri: http://main-service:8081
          predicates:
            - Path=/admin/comment/**
            - Method=GET,DELETE,POST

        # Private Comments Routes
        - id: private_comments
          uri: http://main-service:8081
          predicates:
            - Path=/comment/**
            - Method=GET,POST,PATCH,DELETE

        # Private Requests Routes
        - id: private_requests
          uri: http://main-service:8081
          predicates:
            - Path=/users/*/requests/**
            - Method=GET,POST,PATCH

        # Public Category Routes
        - id: public_categories
          uri: http://main-service:8081
          predicates:
            - Path=/categories/**
            - Method=GET

        # Дополнительные маршруты для специфичных путей Private Comments
        - id: private_comments_event
          uri: http://main-service:8081
          predicates:
            - Path=/comment/event/**
            - Method=POST

        - id: private_comments_user
          uri: http://main-service:8081
          predicates:
            - Path=/comment/user/**
            - Method=GET
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
