  server:
  address: 0.0.0.0
  port: 8080

spring:
  cloud:
    gateway:
      # === Admin API ===
        - id: admin-api
          uri: lb://main-service
          predicates:
            - Path=/admin/**  # Все запросы начинаются с /api/admin
          filters:
            - StripPrefix=1       # Удаляем префикс "/api/admin" → "/"
        
        # === Private API ===
        - id: private-api
          uri: lb://main-service
          predicates:
            - Path=/private/**
          filters:
            - StripPrefix=1
        
        # === Public API ===
        - id: public-api
          uri: lb://main-service
          predicates:
            - Path=/public/**
          filters:
            - StripPrefix=1
        
        # === Общие эндпоинты без префикса ===
        - id: default-api
          uri: lb://main-service
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
