server:
  port: 0

spring:
  application:
    name: stats-server
  jpa:
    hibernate:
      ddl-auto: "none"
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: "always"
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:6432/ewm-stats"
    username: "stat"
    password: "stat"
    sql:
      init:
        schema-locations: "schema.sql"

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        transaction:
          interceptor: TRACE
        JpaTransactionManager: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
