server:
  port: 0

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/ewm-stats"
    username: "stat"
    password: "stat"
  jpa:
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: "always"

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        transaction:
          interceptor: TRACE
        JpaTransactionManager: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
